// Objective-C API for talking to ChemistryBackbone/ChemistryBackbone Go package.
//   gobind -lang=objc ChemistryBackbone/ChemistryBackbone
//
// File is generated by gobind. Do not edit.

#ifndef __ChemistryBackbone_H__
#define __ChemistryBackbone_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class ChemistryBackboneEquation;
@class ChemistryBackboneEquationSection;

@interface ChemistryBackboneEquation : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field Equation.Id with unsupported type: ChemistryBackbone/ChemistryBackbone.EquationId

@property (nonatomic) NSString* _Nonnull title;
@property (nonatomic) NSString* _Nonnull description;
// skipped field Equation.Filters with unsupported type: []ChemistryBackbone/ChemistryBackbone.EquationFilter

// skipped field Equation.Calculation with unsupported type: ChemistryBackbone/ChemistryBackbone.EquationCalculation

// skipped field Equation.FieldLabels with unsupported type: []string

@end

@interface ChemistryBackboneEquationSection : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) NSString* _Nonnull name;
// skipped field EquationSection.Equations with unsupported type: []ChemistryBackbone/ChemistryBackbone.Equation

@end

// skipped const AdvancedEquations with unsupported type: ChemistryBackbone/ChemistryBackbone.EquationFilter

FOUNDATION_EXPORT NSString* _Nonnull const ChemistryBackboneDENSITY_EQUATION_DESCRIPTION;
// skipped const Density1 with unsupported type: ChemistryBackbone/ChemistryBackbone.EquationId

// skipped const Density2 with unsupported type: ChemistryBackbone/ChemistryBackbone.EquationId

// skipped const Density3 with unsupported type: ChemistryBackbone/ChemistryBackbone.EquationId


@interface ChemistryBackbone : NSObject
// skipped variable DensityEquations with unsupported type: ChemistryBackbone/ChemistryBackbone.EquationSection

@end

FOUNDATION_EXPORT NSString* _Nonnull ChemistryBackboneGreetings(NSString* _Nullable name);

#endif
