
// Objective-C API for talking to the following Go packages
//
//	ChemistryBackbone/ChemistryBackbone
//
// File is generated by gomobile bind. Do not edit.
#ifndef __ChemistryBackbone_FRAMEWORK_H__
#define __ChemistryBackbone_FRAMEWORK_H__

#include "ChemistryBackbone.objc.h"
#include "Universe.objc.h"

#endif
